### PR TITLE
Removal of Thread.Sleep

### PR DESCRIPTION
**Pull request by madecode15**
This was ported because Nukkit is a direct clone of PocketMine.

Such crap solutions should not apply to Java, this is unnecessary and every good java developer knows that using Thread.sleep should never be used because it deliberately slows the application down. Java should not need this, it seems more of a PHP hack unnecessary ported to Java.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
@madecode15 just a question, you did test this change before creating a pull request, right?

I'm just asking because I'm on college right now so I can't test your change right now.

**Comment by MrPowerGamerBR** [comment]
Okay, after taking a look at the code... damn, who thought that adding that was a good idea at all?

**Comment by madecode15** [comment]
Yes, as small as it seems ~1ms, it causes "lag"spikes.

Hopefully if Nukkit becomes more active, we can apply this.

I'm surprised Nukkit barley takes advantage of the built in java thread support (which is why I love java, any day over PHP). If the project becomes more active on the main repo, hopefully I'll have time to move chunk loading to a separate thread and part from PocketMine's system.

**Comment by MrPowerGamerBR** [comment]
@madecode15 I forked Nukkit because I needed a good MCPE server software,
however Nukkit development is slower than a turtle and because I don't like
PHP enough to use PocketMine-MP.

I will probably maintain this fork because I need it for my upcoming Pocket
server and because I like messing around with it.

Em 23 de fev de 2017 11:59, "madecode15" <notifications@github.com>
escreveu:

**Comment by torankusu50** [comment]
I have been watching your progress over the past week and have to say keep up the good work to all who is involved. The only nukkit commits I've seen to the main repo of nukkit is to "hack" the version number. I will be using this fork for my "family" server so I really hope you keep it up as its much appreciated <3

**Comment by MrPowerGamerBR** [comment]
Also, the only reason that I would stop updating this fork is **if**:
1. A better and faster MCPE server software in Java is created.
2. If I can get Pocket support working (and stable) in Glowstone.

About the second one, don't worry, it will be open source so anyone can use it.

**Comment by DaMatrix** [comment]
After looking into it a bit more, it would seem that this PR is responsible for https://github.com/Nukkit/Nukkit/issues/1494

**Comment by MrPowerGamerBR** [comment]
@DaMatrix does the latest Nukkit build don't have this issue?

**Comment by DaMatrix** [comment]
nope, and reverting this PR causes the CPU load to dissappear

**Comment by MrPowerGamerBR** [comment]
@DaMatrix try the latest build

**Comment by DaMatrix** [comment]
Ok, testing

**Comment by DaMatrix** [comment]
Can confirm that without this I get 2% CPU load compared to 100% with it.

**Comment by MrPowerGamerBR** [comment]
@DaMatrix so that code was actually used for something!

**Pull request merged**
